server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://sh-cynosdbmysql-grp-4maus0v0.sql.tencentcdb.com:24858/springboot_demo
    username: root
    password: kTDazPk3
  redis:
    host: 112.126.92.36 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package: com.tencent.wxcloudrun.enums


wxpay:
  appId: wx40aef2a640a5077a
  keyPath: key.pem
  certPath: cert.pem
  certP12Path: cert.p12
  platformCertPath: wx_cert.pem
  mchId: 1625995235
  apiKey3: Api-v3 \u5BC6\u94A5
  apiKey: Api \u5BC6\u94A5
  domain: https://ijpay.javen.com


wx:
  miniapp:
    configs:
      - appid: wx40aef2a640a5077a
        secret: a1d975738a46cef50bdcb02ede86208a#
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
